#!/usr/bin/env bash
echo "[update-submodule hook: $1]"

# Call "git submodule update" automatically if the file .gitmodules is changed.

changedfiles=$(git diff-tree --no-commit-id --name-only HEAD@\{1\} HEAD)

if [[ "${changedfiles[*]}" =~ \.gitmodules ]]; then
    echo "initializing & updating submodule(s)"
    git submodule update --init --recursive
    echo ""
fi
