<pdffunction:openObject return="all" />
<pdffunction:saveState />
<pdffunction:setStrokeColor arg="0" arg="0" arg="0" arg="1" />
<pdffunction:line arg="20" arg="40" arg="578" arg="40" />
<pdffunction:line arg="20" arg="822" arg="578" arg="822" />
<pdffunction:addText arg="50" arg="34" arg="6" arg="Generated by phpDocumentor v{$phpdocversion} http://www.phpdoc.org - http://www.sourceforge.net/projects/phpdocu" />
<pdffunction:restoreState />
<pdffunction:closeObject />
{* note that object can be told to appear on just odd or even pages by changing
'all' to 'odd' or 'even'. *}
<pdffunction:addObject arg=$all arg="all" />