[phases.setup]
nixPkgs = [
    '(php82.withExtensions (pe: pe.enabled ++ []))',
    'nginx',
    'libmysqlclient',
    'php82Packages.composer',
    'nodejs_18',
    'npm-9_x'
]

[phases.install]
cmds = [
    'mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx',
    'composer install --ignore-platform-reqs',
    'npm ci'
]

[start]
cmd = 'node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)'