<refentry id="{@id}">
 <refnamediv>
  <refname>Writing templates for the CHMdefault Converter</refname>
  <refpurpose>Learn which template variables are available for use in an CHM:default template</refpurpose>
 </refnamediv>
 <refsynopsisdiv>
  <authorgroup>
   <author>
    Joshua Eichorn
    <authorblurb>
     {@link mailto:jeichorn@phpdoc.org jeichorn@phpdoc.org}
    </authorblurb>
   </author>
   <author>
    Gregory Beaver
    <authorblurb>
     {@link mailto:cellog@sourceforge.com cellog@sourceforge.com}
    </authorblurb>
   </author>
  </authorgroup>
 </refsynopsisdiv>
 <refsect1 id="{@id intro}">
  <title>CHM:default:* Introduction</title>
  <para>This documentation deals only with adding a new template to the CHMdefault Converter.  To learn how to use phpDocumentor, read the {@tutorial phpDocumentor/phpDocumentor.pkg}.  To learn how to write a new Converter, read {@tutorial Converters.pkg}</para>
 </refsect1>
 <refsect1 id="{@id overview}">
  <para>
   To generate a CHM file, go to {@link http://go.microsoft.com/fwlink/?LinkId=14188} and download Microsoft's Help Workshop.
  </para>
 </refsect1>
</refentry>
