<div align="center"><h1>{$maintitle}</h1></div>
<b>Welcome to {$package}!</b><br />
<br />
This documentation was generated by <a href="{$phpdocwebsite}">phpDocumentor v{$phpdocversion}</a><br />

