<?php
/**
 * Piwik - Open source web analytics
 *
 * @link http://piwik.org
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 * @version $Id$
 *
 * @category Piwik
 * @package DataFiles
 */

/*
 * Language database
 */
if(!isset($GLOBALS['Piwik_LanguageList']))
{
	// Reference: ISO 639-1 alpha-2
	$GLOBALS['Piwik_LanguageList'] = array(
		'af' => 'Afrikaans',
		'am' => 'Amharic',
		'ar' => 'Arabic',
		'ay' => 'Aymara',
		'az' => 'Azerbaijani',
		'be' => 'Byelorussian',
		'bg' => 'Bulgarian',
		'bi' => 'Bislama',
		'bn' => 'Bengali',
		'bs' => 'Bosnian',
		'ca' => 'Catalan',
		'cs' => 'Czech',
		'cy' => 'Welsh',
		'da' => 'Danish',
		'de' => 'German',
		'dv' => 'Divehi',
		'dz' => 'Bhutani',
		'el' => 'Greek',
		'en' => 'English',
		'es' => 'Spanish',
		'et' => 'Estonian',
		'eu' => 'Basque',
		'fa' => 'Persian',
		'fi' => 'Finnish',
		'fj' => 'Fijian',
		'fo' => 'Faroese',
		'fr' => 'French',
		'fy' => 'Frisian',
		'ga' => 'Irish',
		'gl' => 'Galician',
		'gn' => 'Guarani',
		'he' => 'Hebrew',
		'hi' => 'Hindi',
		'ho' => 'Hiri Motu',
		'hr' => 'Croatian',
		'ht' => 'Haitian; Haitian Creole',
		'hu' => 'Hungarian',
		'hy' => 'Armenian',
		'id' => 'Indonesian',
		'is' => 'Icelandic',
		'it' => 'Italian',
		'ja' => 'Japanese',
		'ka' => 'Georgian',
		'kk' => 'Kazakh',
		'kl' => 'Kalaalisut',
		'km' => 'Khmer',
		'ko' => 'Korean',
		'ky' => 'Kirghiz',
		'la' => 'Latin',
		'lb' => 'Luxembourgish; Letzeburgesch',
		'lo' => 'Lao',
		'lt' => 'Lithuanian',
		'lv' => 'Latvian',
		'mg' => 'Malagasy',
		'mh' => 'Marshallese',
		'mi' => 'Maori',
		'mk' => 'Macedonian',
		'mn' => 'Mongolian',
		'mo' => 'Moldovan',
		'ms' => 'Malay',
		'mt' => 'Maltese',
		'my' => 'Burmese',
		'na' => 'Nauru',
		'nb' => 'Norwegian Bokmå',
		'ne' => 'Nepali',
		'nl' => 'Dutch',
		'nn' => 'Norwegian Nynorsk',
		'no' => 'Norwegian',
		'nr' => 'Ndebele',
		'ny' => 'Chichewa',
		'pl' => 'Polish',
		'ps' => 'Pushto',
		'pt' => 'Portuguese',
		'qu' => 'Quechua',
		'rm' => 'Romanche',
		'rn' => 'Rundi',
		'ro' => 'Romanian',
		'ru' => 'Russian',
		'rw' => 'Kinyarwanda',
		'se' => 'Northern Sami',
		'sg' => 'Sango',
		'si' => 'Singhalese',
		'sk' => 'Slovak',
		'sl' => 'Slovenian',
		'sm' => 'Samoan',
		'so' => 'Somali',
		'sq' => 'Albanian',
		'sr' => 'Serbian',
		'ss' => 'Swati',
		'st' => 'Sotho',
		'sv' => 'Swedish',
		'sw' => 'Swahili',
		'ta' => 'Tamil',
		'tg' => 'Tajik',
		'th' => 'Thai',
		'ti' => 'Tigrinya',
		'tk' => 'Turkmen',
		'tl' => 'Tagalog',
		'tn' => 'Tswana',
		'to' => 'Tonga (Tonga Islands)',
		'tr' => 'Turkish',
		'ts' => 'Tsonga',
		'uk' => 'Ukrainian',
		'ur' => 'Urdu',
		'uz' => 'Uzbek',
		've' => 'Venda',
		'vi' => 'Vietnamese',
		'xh' => 'Xhosa',
		'zh' => 'Chinese',
		'zu' => 'Zulu',

		// not officially assigned
		'ki' => 'Gilbertese',
		'me' => 'Montenegrin',
		'pw' => 'Palauan',
		'za' => 'Pedi',
		'sc' => 'Seselwa',
		'km' => 'Shikomor',
		'tl' => 'Tetum',
		'pg' => 'Tok Pisin',
		'tv' => 'Tuvaluan',
	);
}
