/*!
 * Matomo - free/libre analytics platform
 *
 * @link    https://matomo.org
 * @license https://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */

/* eslint-disable */

// AUTO-GENERATED - DO NOT EDIT.
//
// Regenerated by plugins/CoreVue/polyfills/scripts/generate-corejs-imports.mjs as part of
// `./console vue:build-polyfill`. It lists the exact core-js modules used by the Vue sources
// under plugins/*/vue/src for the browsers in .browserslistrc, so the shared polyfill only ships
// the polyfills that are actually needed instead of the whole of core-js/stable.

import 'core-js/modules/es.array.flat.js';
import 'core-js/modules/es.array.flat-map.js';
import 'core-js/modules/es.array.includes.js';
import 'core-js/modules/es.array.iterator.js';
import 'core-js/modules/es.array.push.js';
import 'core-js/modules/es.array.reduce.js';
import 'core-js/modules/es.array.reverse.js';
import 'core-js/modules/es.array.sort.js';
import 'core-js/modules/es.array.unscopables.flat.js';
import 'core-js/modules/es.array.unscopables.flat-map.js';
import 'core-js/modules/es.array.unshift.js';
import 'core-js/modules/es.error.cause.js';
import 'core-js/modules/es.iterator.constructor.js';
import 'core-js/modules/es.iterator.every.js';
import 'core-js/modules/es.iterator.filter.js';
import 'core-js/modules/es.iterator.find.js';
import 'core-js/modules/es.iterator.flat-map.js';
import 'core-js/modules/es.iterator.for-each.js';
import 'core-js/modules/es.iterator.map.js';
import 'core-js/modules/es.iterator.reduce.js';
import 'core-js/modules/es.iterator.some.js';
import 'core-js/modules/es.json.parse.js';
import 'core-js/modules/es.json.stringify.js';
import 'core-js/modules/es.map.get-or-insert.js';
import 'core-js/modules/es.map.get-or-insert-computed.js';
import 'core-js/modules/es.number.to-fixed.js';
import 'core-js/modules/es.object.assign.js';
import 'core-js/modules/es.object.entries.js';
import 'core-js/modules/es.object.from-entries.js';
import 'core-js/modules/es.object.get-own-property-descriptors.js';
import 'core-js/modules/es.object.values.js';
import 'core-js/modules/es.parse-float.js';
import 'core-js/modules/es.parse-int.js';
import 'core-js/modules/es.promise.js';
import 'core-js/modules/es.promise.all-settled.js';
import 'core-js/modules/es.promise.finally.js';
import 'core-js/modules/es.regexp.constructor.js';
import 'core-js/modules/es.regexp.dot-all.js';
import 'core-js/modules/es.regexp.exec.js';
import 'core-js/modules/es.regexp.test.js';
import 'core-js/modules/es.regexp.to-string.js';
import 'core-js/modules/es.set.difference.v2.js';
import 'core-js/modules/es.set.intersection.v2.js';
import 'core-js/modules/es.set.is-disjoint-from.v2.js';
import 'core-js/modules/es.set.is-subset-of.v2.js';
import 'core-js/modules/es.set.is-superset-of.v2.js';
import 'core-js/modules/es.set.symmetric-difference.v2.js';
import 'core-js/modules/es.set.union.v2.js';
import 'core-js/modules/es.string.includes.js';
import 'core-js/modules/es.string.match.js';
import 'core-js/modules/es.string.pad-start.js';
import 'core-js/modules/es.string.replace.js';
import 'core-js/modules/es.string.replace-all.js';
import 'core-js/modules/es.string.search.js';
import 'core-js/modules/es.string.split.js';
import 'core-js/modules/es.string.starts-with.js';
import 'core-js/modules/es.string.trim.js';
import 'core-js/modules/es.symbol.description.js';
import 'core-js/modules/es.weak-map.js';
import 'core-js/modules/es.weak-map.get-or-insert.js';
import 'core-js/modules/es.weak-map.get-or-insert-computed.js';
import 'core-js/modules/web.dom-collections.for-each.js';
import 'core-js/modules/web.dom-collections.iterator.js';
import 'core-js/modules/web.url.js';
import 'core-js/modules/web.url-search-params.js';
import 'core-js/modules/web.url-search-params.delete.js';
import 'core-js/modules/web.url-search-params.has.js';
import 'core-js/modules/web.url-search-params.size.js';
import 'core-js/modules/web.url.to-json.js';
