#!/bin/bash

## Description: Initialize Matomo PHP Tests
## Usage: matomo:init:tests-php
## Example: ddev matomo:init:tests-php

# @see: https://developer.matomo.org/guides/tests-php

echo "Run npm install ..."
ddev npm install

echo "Run composer install to install PHPUnit ..."
ddev composer install

echo "TODO: Configure section tests in config/config.ini.php "
echo "@see https://developer.matomo.org/guides/tests-php#requirements"
read -n 1 -s -r -p "Press any key when ready to continue ..."
echo ""

echo "Enabled development mode ..."
ddev exec './console development:enable'

echo "Migrate the test database: setup OmniFixture ..."
ddev exec './console tests:setup-fixture OmniFixture'

echo "Done: Matomo PHP Tests might be initialized."
echo ""
