#!/bin/bash

## Description: Initialize Matomo UI Tests
## Usage: matomo:init:tests-ui
## Example: ddev matomo:init:tests-ui

# @see: https://developer.matomo.org/guides/tests-ui

echo "TODO: Locally install the git-lfs extension to be able to download and commit UI screenshots."
echo "@see https://github.com/git-lfs/git-lfs#installing"
echo "@see https://git-lfs.com/"
read -n 1 -s -r -p "Press any key when ready to continue ..."
echo ""

echo "Install the JavaScript dependencies for the UI tests ..."
ddev exec 'cd tests/lib/screenshot-testing && npm install'

echo "Git: pull the example screenshots for the tests ..."
git lfs pull --exclude=

echo "TODO: Configure UI tests in tests/UI/config.js"
echo "@see https://developer.matomo.org/guides/tests-ui#configuring-ui-tests"
read -n 1 -s -r -p "Press any key when ready to continue ..."
echo ""

echo "Done: Matomo UI Tests might be initialized."
echo ""
