#!/bin/bash

## Description: Initialize Matomo base install
## Usage: matomo:init:base
## Example: ddev matomo:init:base

echo "Run composer install ..."
ddev composer install

echo "Done: Matomo base install might be ready."
