/*!
 * Matomo - free/libre analytics platform
 *
 * Finds the Mocha UI specs, writes one Playwright test file per spec into legacy/generated, and splits all
 * test files into shards of similar duration.
 *
 * @link    https://matomo.org
 * @license https://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../../..');
const PLAYWRIGHT_DIR = path.resolve(__dirname, '..');
const GENERATED_DIR = path.join(__dirname, 'generated');
const DEFAULT_DURATION = 60; // seconds, for specs without a measured duration

// specs rewritten for Playwright in specs/, so their Mocha versions don't run twice
const PORTED = new Set([
  'tests/UI/specs/Comparison_spec.js',
  'tests/UI/specs/PeriodSelector_spec.js',
  'tests/UI/specs/ViewDataTable_spec.js',
]);

function walk(dir, result = []) {
  if (!fs.existsSync(dir)) {
    return result;
  }
  for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, item.name);
    if (item.isDirectory() && !['node_modules', 'vendor'].includes(item.name)) {
      walk(full, result);
    } else if (item.isFile() && item.name.endsWith('_spec.js')) {
      result.push(full);
    }
  }
  return result;
}

/** The specs tests:run-ui runs in CI: tests/UI/specs, and every plugin's tests and Test folders. */
function legacySpecs() {
  const specs = walk(path.join(ROOT, 'tests/UI/specs')).map((file) => ({ file, plugin: null }));
  for (const plugin of fs.readdirSync(path.join(ROOT, 'plugins')).sort()) {
    for (const dir of ['tests', 'Test']) {
      walk(path.join(ROOT, 'plugins', plugin, dir)).forEach((file) => specs.push({ file, plugin }));
    }
  }
  return specs
    .map((spec) => ({ ...spec, file: path.relative(ROOT, spec.file) }))
    .filter((spec) => !PORTED.has(spec.file));
}

function wrapperPath(spec) {
  return path.join(GENERATED_DIR, spec.plugin || 'core', path.basename(spec.file).replace(/\.js$/, '.spec.js'));
}

/** Writes the Playwright test files for the legacy specs, rewriting only what changed. */
function writeWrappers() {
  const wanted = new Map(legacySpecs().map((spec) => [wrapperPath(spec), spec]));
  for (const [file, spec] of wanted) {
    const relativeRuntime = path.relative(path.dirname(file), path.join(__dirname, 'runtime')).split(path.sep).join('/');
    const content = `// Generated by tests/playwright/legacy/specs.js, do not edit.\nrequire('${relativeRuntime}').run(${JSON.stringify({ file: spec.file, plugin: spec.plugin })});\n`;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) {
      fs.writeFileSync(file, content);
    }
  }
  for (const file of listSpecFiles(GENERATED_DIR)) {
    if (!wanted.has(file)) {
      fs.rmSync(file);
    }
  }
  return [...wanted.entries()].map(([file, spec]) => ({ file, source: spec.file }));
}

function listSpecFiles(dir, result = []) {
  if (!fs.existsSync(dir)) {
    return result;
  }
  for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, item.name);
    if (item.isDirectory()) {
      listSpecFiles(full, result);
    } else if (item.name.endsWith('.spec.js')) {
      result.push(full);
    }
  }
  return result;
}

/**
 * All test files with their expected duration. Legacy files are measured by their Mocha spec, and the
 * durations come from legacy/timings.json (seconds per file, taken from CI runs).
 */
function testFiles() {
  const timings = JSON.parse(fs.readFileSync(path.join(__dirname, 'timings.json'), 'utf8'));
  const duration = (key) => timings[key] ?? DEFAULT_DURATION;
  const ported = listSpecFiles(path.join(PLAYWRIGHT_DIR, 'specs'))
    .map((file) => ({ file, seconds: duration(path.relative(ROOT, file)) }));
  const legacy = writeWrappers().map(({ file, source }) => ({ file, seconds: duration(source) }));
  return ported.concat(legacy);
}

/**
 * The files of one shard ("2/10"): longest files first, each onto the shard with the least work so far,
 * so the shards take about the same time.
 */
function shardFiles(shard) {
  const files = testFiles();
  if (!shard) {
    return files.map(({ file }) => file);
  }
  const [index, total] = shard.split('/').map(Number);
  const bins = Array.from({ length: total }, () => ({ seconds: 0, files: [] }));
  for (const entry of files.sort((a, b) => b.seconds - a.seconds || a.file.localeCompare(b.file))) {
    const bin = bins.reduce((least, candidate) => (candidate.seconds < least.seconds ? candidate : least));
    bin.seconds += entry.seconds;
    bin.files.push(entry.file);
  }
  return bins[index - 1].files;
}

module.exports = { legacySpecs, shardFiles, testFiles };
