; <?php exit; ?> DO NOT REMOVE THIS LINE
; file automatically generated or modified by Piwik; you can manually override the default values in global.ini.php by redefining them in this file.
[database]
host = "localhost"
username = "root"
password = "secure"
dbname = "piwik2"
tables_prefix = "piwik_"
adapter = "PDO\MYSQL"
charset = "utf8"

[database_tests]
password = "secure"

[log]
log_writers[] = "file"
log_writers[] = "database"
logger_message[] = "database"
logger_error[] = "database"
logger_exception[] = "database"

[Debug]
track_visits_inside_piwik_ui = 1
disable_merged_assets = 1
enable_sql_profilerr = 1

[General]
trusted_hosts[] = "apache.piwik"
trusted_hosts[] = "nginx.piwik"
salt = "0e7ba14c88cf21e24d4e038d4b6800b2"

[mail]
transport = "smtp"
host = "smtp.gmail.com"
type = "Login"
username = "thomas.steur@googlemail.com"
password = "voekuphysyqaohpk"
encryption = "ssl"

[Plugins]
Plugins[] = "CorePluginsAdmin"
Plugins[] = "CoreAdminHome"
Plugins[] = "CoreHome"
Plugins[] = "CoreVisualizations"
Plugins[] = "Proxy"
Plugins[] = "API"
Plugins[] = "ExamplePlugin"
Plugins[] = "Widgetize"
Plugins[] = "Transitions"
Plugins[] = "LanguagesManager"
Plugins[] = "Actions"
Plugins[] = "Dashboard"
Plugins[] = "MultiSites"
Plugins[] = "Referrers"
Plugins[] = "UserSettings"
Plugins[] = "Goals"
Plugins[] = "SEO"
Plugins[] = "Events"
Plugins[] = "UserCountry"
Plugins[] = "VisitsSummary"
Plugins[] = "VisitFrequency"
Plugins[] = "VisitTime"
Plugins[] = "VisitorInterest"
Plugins[] = "ExampleAPI"
Plugins[] = "ExampleRssWidget"
Plugins[] = "Provider"
Plugins[] = "Feedback"
Plugins[] = "Login"
Plugins[] = "UsersManager"
Plugins[] = "SitesManager"
Plugins[] = "Installation"
Plugins[] = "CoreUpdater"
Plugins[] = "CoreConsole"
Plugins[] = "UserCountryMap"
Plugins[] = "Live"
Plugins[] = "CustomVariables"
Plugins[] = "PrivacyManager"
Plugins[] = "ImageGraph"
Plugins[] = "Annotations"
Plugins[] = "Overlay"
Plugins[] = "SegmentEditor"
Plugins[] = "Morpheus"
Plugins[] = "Zeitgeist"
Plugins[] = "ScheduledReports"
Plugins[] = "CustomAlerts"
Plugins[] = "TasksTimetable"
Plugins[] = "MobileMessaging"

[PluginsInstalled]
PluginsInstalled[] = "Login"
PluginsInstalled[] = "CoreAdminHome"
PluginsInstalled[] = "UsersManager"
PluginsInstalled[] = "SitesManager"
PluginsInstalled[] = "Installation"
PluginsInstalled[] = "CorePluginsAdmin"
PluginsInstalled[] = "CoreHome"
PluginsInstalled[] = "CoreVisualizations"
PluginsInstalled[] = "Proxy"
PluginsInstalled[] = "API"
PluginsInstalled[] = "ExamplePlugin"
PluginsInstalled[] = "Widgetize"
PluginsInstalled[] = "Transitions"
PluginsInstalled[] = "LanguagesManager"
PluginsInstalled[] = "Actions"
PluginsInstalled[] = "Dashboard"
PluginsInstalled[] = "MultiSites"
PluginsInstalled[] = "Referrers"
PluginsInstalled[] = "UserSettings"
PluginsInstalled[] = "Goals"
PluginsInstalled[] = "SEO"
PluginsInstalled[] = "Events"
PluginsInstalled[] = "UserCountry"
PluginsInstalled[] = "VisitsSummary"
PluginsInstalled[] = "VisitFrequency"
PluginsInstalled[] = "VisitTime"
PluginsInstalled[] = "VisitorInterest"
PluginsInstalled[] = "ExampleAPI"
PluginsInstalled[] = "ExampleRssWidget"
PluginsInstalled[] = "Provider"
PluginsInstalled[] = "Feedback"
PluginsInstalled[] = "CoreUpdater"
PluginsInstalled[] = "CoreConsole"
PluginsInstalled[] = "ScheduledReports"
PluginsInstalled[] = "UserCountryMap"
PluginsInstalled[] = "Live"
PluginsInstalled[] = "CustomVariables"
PluginsInstalled[] = "PrivacyManager"
PluginsInstalled[] = "ImageGraph"
PluginsInstalled[] = "DoNotTrack"
PluginsInstalled[] = "Annotations"
PluginsInstalled[] = "MobileMessaging"
PluginsInstalled[] = "Overlay"
PluginsInstalled[] = "SegmentEditor"
PluginsInstalled[] = "Morpheus"
PluginsInstalled[] = "Zeitgeist"
PluginsInstalled[] = "CustomAlerts"
PluginsInstalled[] = "LiveTab"
PluginsInstalled[] = "AnonymizeIP"
PluginsInstalled[] = "DBStats"
PluginsInstalled[] = "DevicesDetection"
PluginsInstalled[] = "ExampleCommand"
PluginsInstalled[] = "ExampleSettingsPlugin"
PluginsInstalled[] = "ExampleTheme"
PluginsInstalled[] = "ExampleUI"
PluginsInstalled[] = "ExampleVisualization"
PluginsInstalled[] = "LeftMenu"
PluginsInstalled[] = "VisitorGenerator"
PluginsInstalled[] = "TasksTimetable"

[Plugins_Tracker]
Plugins_Tracker[] = "Provider"
Plugins_Tracker[] = "Goals"
Plugins_Tracker[] = "UserCountry"
Plugins_Tracker[] = "UsersManager"
Plugins_Tracker[] = "SitesManager"
Plugins_Tracker[] = "DevicesDetection"
Plugins_Tracker[] = "PrivacyManager"
Plugins_Tracker[] = "Login"
