<?php

/**
 * Matomo - free/libre analytics platform
 *
 * @link    https://matomo.org
 * @license https://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */

namespace Piwik\Plugins\UsersManager\tests\System;

use Piwik\Access;
use Piwik\Access\Capability;
use Piwik\Container\StaticContainer;
use Piwik\Date;
use Piwik\API\Request;
use Piwik\Piwik;
use Piwik\Plugins\UsersManager\API;
use Piwik\Plugins\UsersManager\Model;
use Piwik\Plugins\UsersManager\tests\Fixtures\ManyUsers;
use Piwik\Tests\Framework\TestCase\SystemTestCase;

class TestWriteCap extends Capability
{
    public const ID = 'test_write_cap';

    public function getId(): string
    {
        return self::ID;
    }

    public function getCategory(): string
    {
        return 'Test';
    }

    public function getName(): string
    {
        return 'WriteCap';
    }

    public function getDescription(): string
    {
        return '';
    }

    public function getIncludedInRoles(): array
    {
        return [];
    }
}

/**
 * @group UsersManager
 * @group ApiTest
 * @group Plugins
 */
class ApiTest extends SystemTestCase
{
    /**
     * @var ManyUsers
     */
    public static $fixture = null; // initialized below class definition

    /**
     * @var API
     */
    private $api;

    /**
     * @var Model
     */
    private $model;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->api = API::getInstance();
        $this->model = new Model();

        Access::getInstance()->setSuperUserAccess(true);
    }

    private function setAnonymousUser(): void
    {
        $auth = StaticContainer::get('Piwik\Auth');
        $auth->setLogin('anonymous');
        $auth->setTokenAuth('anonymous');
        $auth->setPasswordHash(null);

        Access::getInstance()->setSuperUserAccess(false);
        Access::getInstance()->reloadAccess($auth);
    }

    /**
     * @dataProvider getApiForTesting
     */
    public function testApi($api, $params = [])
    {
        $apiId = implode('_', $params);
        $logins = [
            'login1' => 'when_superuseraccess',
            'login2' => 'when_adminaccess',
            'login4' => 'when_viewaccess',
        ];

        // login1 = super user, login2 = some admin access, login4 = only view access
        foreach ($logins as $login => $appendix) {
            $params['token_auth'] = self::$fixture->users[$login]['token'];
            $xmlFieldsToRemove = [
                'date_registered',
                'invite_token',
                'invite_accept_at',
                'invite_expired_at',
                'last_seen',
                'last_seen_ago',
                'password',
                'token_auth',
                'ts_password_modified',
                'idchange_last_viewed',
                'invite_status',
                'ts_changes_shown',
                'ts_last_seen',
            ];

            $this->runAnyApiTest($api, $apiId . '_' . $appendix, $params, array('xmlFieldsToRemove' => $xmlFieldsToRemove));
        }
    }

    public function testGetUserPreferenceLoginIsOptional()
    {
        $response = Request::processRequest('UsersManager.getUserPreference', array(
            'preferenceName' => API::PREFERENCE_DEFAULT_REPORT,
        ));
        $this->assertEquals('1', $response);

        $response = Request::processRequest('UsersManager.getUserPreference', array(
            'preferenceName' => API::PREFERENCE_DEFAULT_REPORT_DATE,
        ));
        $this->assertEquals('yesterday', $response);
    }

    public function testGetUserPreferenceLoginCanBeSet()
    {
        $response = Request::processRequest('UsersManager.getUserPreference', array(
            'userLogin' => Piwik::getCurrentUserLogin(),
            'preferenceName' => API::PREFERENCE_DEFAULT_REPORT_DATE,
        ));
        $this->assertEquals('yesterday', $response);

        // user not exists
        $response = Request::processRequest('UsersManager.getUserPreference', array(
            'userLogin' => 'foo',
            'preferenceName' => API::PREFERENCE_DEFAULT_REPORT_DATE,
        ));
        $this->assertEquals('yesterday', $response);
    }

    public function getApiForTesting()
    {
        $apiToTest = array(
            array('UsersManager.getUsers'),
            array('UsersManager.getUsersLogin'),
            array('UsersManager.getUsersAccessFromSite', array('idSite' => 6)), // admin user has admin access for this
            array('UsersManager.getUsersAccessFromSite', array('idSite' => 3)), // admin user has only view access for this, should not see anything
            array('UsersManager.getUsersSitesFromAccess', array('access' => 'admin')),
            array('UsersManager.getUsersWithSiteAccess', array('idSite' => 3, 'access' => 'admin')),
            array('UsersManager.getUser', array('userLogin' => 'login1')),
            array('UsersManager.getUser', array('userLogin' => 'login2')),
            array('UsersManager.getUser', array('userLogin' => 'login4')),
            array('UsersManager.getUser', array('userLogin' => 'login6')),
        );

        return $apiToTest;
    }

    public function testCreateAppSpecificTokenAuthWithCrypticPassword()
    {
        $password = 'p§$%"@&<~#\'\\/+ >*^!°p';
        API::$UPDATE_USER_REQUIRE_PASSWORD_CONFIRMATION = false;
        $this->api->updateUser('login6', $password);
        API::$UPDATE_USER_REQUIRE_PASSWORD_CONFIRMATION = true;
        $this->model->deleteAllTokensForUser('login6');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login6', $password, 'test');
        $this->assertMd5($token);

        $user = $this->model->getUserByTokenAuth($token);
        $this->assertSame('login6', $user['login']);
    }

    public function testCreateAppSpecificTokenAuth()
    {
        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login1', 'password', 'test');
        $this->assertMd5($token);

        $user = $this->model->getUserByTokenAuth($token);
        $this->assertSame('login1', $user['login']);

        $tokenMetadata = $this->model->getTokenMetadataByTokenAuth($token);
        $this->assertNull($tokenMetadata['access_level']);
    }

    public function testCreateAppSpecificTokenAuthCanLoginByEmail()
    {
        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login1@example.com', 'password', 'test');
        $this->assertMd5($token);

        $user = $this->model->getUserByTokenAuth($token);
        $this->assertSame('login1', $user['login']);
    }

    public function testCreateAppSpecificTokenAuthFailsWhenPasswordNotValid()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessage('The current password you entered is not correct.');

        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $this->api->createAppSpecificTokenAuth('login1', 'foooooo', 'test');
    }

    public function testCreateAppSpecificTokenAuthWithExpireDate()
    {
        $this->model->deleteAllTokensForUser('login1');

        $expiryDate = (new \DateTime())->modify('+1 day');

        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login1', 'password', 'test', $expiryDate->format('Y-m-d H:i:s'));
        $this->assertMd5($token);

        $tokens = $this->model->getAllNonSystemTokensForLogin('login1');
        $this->assertEquals($this->model->hashTokenAuth($token), $tokens[0]['password']);
        $this->assertEquals('login1', $tokens[0]['login']);
        $this->assertEquals('test', $tokens[0]['description']);
        $this->assertEquals($expiryDate->format('Y-m-d H:i:s'), $tokens[0]['date_expired']);
        $this->assertNull($tokens[0]['access_level']);
    }

    public function testCreateAppSpecificTokenAuthWithExpireHours()
    {
        $expireInHours = 48;
        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login1', 'password', 'test', null, $expireInHours);
        $this->assertMd5($token);

        $tokens = $this->model->getAllNonSystemTokensForLogin('login1');
        $this->assertEquals($this->model->hashTokenAuth($token), $tokens[0]['password']);
        $this->assertEquals('login1', $tokens[0]['login']);
        $this->assertNotEmpty($tokens[0]['date_expired']);
        $this->assertNull($tokens[0]['access_level']);

        $dateExpired = Date::factory($tokens[0]['date_expired']);
        $dateExpired->isLater(Date::now()->addHour($expireInHours - 1));
        $dateExpired->isEarlier(Date::now()->addHour($expireInHours + 1));
    }

    public function testCreateAppSpecificTokenAuthWithExplicitAccessLevel()
    {
        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login1', 'password', 'test', null, 0, false, 'write');
        $this->assertMd5($token);

        $tokenMetadata = $this->model->getTokenMetadataByTokenAuth($token);
        $this->assertSame('write', $tokenMetadata['access_level']);
    }

    public function testCreateAppSpecificTokenAuthWithoutAccessLevelKeepsTokenUnscopedForAdminUser()
    {
        $this->model->deleteAllTokensForUser('login2');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login2', 'password', 'test');
        $this->assertMd5($token);

        $tokenMetadata = $this->model->getTokenMetadataByTokenAuth($token);
        $this->assertNull($tokenMetadata['access_level']);
    }

    public function testCreateAppSpecificTokenAuthWithoutAccessLevelKeepsTokenUnscopedForViewOnlyUser()
    {
        $this->model->deleteAllTokensForUser('login4');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login4', 'password', 'test');
        $this->assertMd5($token);

        $tokenMetadata = $this->model->getTokenMetadataByTokenAuth($token);
        $this->assertNull($tokenMetadata['access_level']);
    }

    public function testCreateAppSpecificTokenAuthWithoutAccessLevelKeepsExplicitCapabilities()
    {
        $this->api->setUserAccess('login2', 'write', [1]);
        $this->api->addCapabilities('login2', TestWriteCap::ID, [1]);
        $this->model->deleteAllTokensForUser('login2');

        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login2', 'password', 'test');
        $this->assertMd5($token);

        // Drive the auth flow as the token request would, then inspect Access::getInstance() directly.
        // We cannot verify via UsersManager.getSitesAccessForUser because that API filters results to
        // sites the caller has admin access on; setUserAccess('write', [1]) downgrades login2 to write
        // on site 1, so login2 would not see site 1 in its own filtered admin view.
        $_GET['token_auth'] = $token;

        try {
            /** @var \Piwik\Auth $auth */
            $auth = \Piwik\Container\StaticContainer::get(\Piwik\Auth::class);
            $auth->setLogin(null);
            $auth->setPasswordHash(null);
            $auth->setPassword(null);
            $auth->setTokenAuth($token);

            $access = Access::getInstance();
            $access->setSuperUserAccess(false);
            $this->assertTrue($access->reloadAccess($auth));

            $this->assertSame('login2', $access->getLogin());
            $this->assertSame('write', $access->getRoleForSite(1));
            // checkUserHasCapability throws NoAccessException when the capability is missing.
            $access->checkUserHasCapability(1, TestWriteCap::ID);
        } finally {
            unset($_GET['token_auth']);
            Access::getInstance()->setSuperUserAccess(true);
            Access::getInstance()->reloadAccess();
        }
    }

    public function testCreateAppSpecificTokenAuthFailsWhenAccessLevelInvalid()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessage('The parameter access must have one of the following values');

        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $this->api->createAppSpecificTokenAuth('login1', 'password', 'test', null, 0, false, 'foobar');
    }

    public function testCreateAppSpecificTokenAuthCoercesEmptyAccessLevelToUnscoped()
    {
        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login1', 'password', 'test', null, 0, false, '');
        $this->assertMd5($token);

        $tokenMetadata = $this->model->getTokenMetadataByTokenAuth($token);
        $this->assertNull($tokenMetadata['access_level']);
    }

    public function testCreateAppSpecificTokenAuthFailsWhenAccessLevelIsInvalidFalsyString()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessage('The parameter access must have one of the following values');

        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $this->api->createAppSpecificTokenAuth('login1', 'password', 'test', null, 0, false, '0');
    }

    public function testCreateAppSpecificTokenAuthFailsWhenAccessLevelIsTooHigh()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessage(Piwik::translate('UsersManager_InvalidTokenAccessLevelTooHigh'));

        $this->model->deleteAllTokensForUser('login4');
        $this->setAnonymousUser();
        $this->api->createAppSpecificTokenAuth('login4', 'password', 'test', null, 0, false, 'admin');
    }

    public function testScopedTokenCannotUseForceApiSession()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessage('Scoped tokens cannot be used with force_api_session.');

        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login1', 'password', 'test', null, 0, false, 'write');

        $_GET['token_auth'] = $token;
        $_GET['force_api_session'] = 1;

        try {
            Request::processRequest('API.getPiwikVersion', [
                'token_auth' => $token,
                'force_api_session' => 1,
                'format' => 'original',
            ]);
        } finally {
            unset($_GET['token_auth']);
            unset($_GET['force_api_session']);
        }
    }

    public function testScopedTokenReloadDoesNotKeepExistingSuperuserAccess()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessage("requires 'admin' access");

        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login1', 'password', 'test', null, 0, false, 'view');

        Access::getInstance()->setSuperUserAccess(true);
        $_GET['token_auth'] = $token;

        try {
            Request::processRequest('UsersManager.setUserAccess', [
                'userLogin' => 'login4',
                'access' => 'view',
                'idSites' => 1,
                'token_auth' => $token,
                'format' => 'original',
            ]);
        } finally {
            unset($_GET['token_auth']);
            Access::getInstance()->setSuperUserAccess(false);
        }
    }

    public function testLegacyTokenCanUseForceApiSession()
    {
        // Prior tests delete login1's tokens, so create a fresh legacy token (access_level=null)
        // directly via the model to avoid depending on the fixture token still being present.
        $this->model->deleteAllTokensForUser('login1');
        $legacyToken = $this->model->generateRandomTokenAuth();
        $this->model->addTokenAuth('login1', $legacyToken, 'legacy', Date::now()->getDatetime(), null, false, false, null);

        $_GET['token_auth'] = $legacyToken;
        $_GET['force_api_session'] = 1;

        try {
            $result = Request::processRequest('API.getPiwikVersion', [
                'token_auth' => $legacyToken,
                'force_api_session' => 1,
                'format' => 'original',
            ]);
            $this->assertNotEmpty($result);
        } finally {
            unset($_GET['token_auth']);
            unset($_GET['force_api_session']);
        }
    }

    public function testSuperuserScopedTokenCanUseForceApiSession()
    {
        $this->model->deleteAllTokensForUser('login1');
        $this->setAnonymousUser();
        $token = $this->api->createAppSpecificTokenAuth('login1', 'password', 'test', null, 0, false, 'superuser');

        $_GET['token_auth'] = $token;
        $_GET['force_api_session'] = 1;

        try {
            $result = Request::processRequest('API.getPiwikVersion', [
                'token_auth' => $token,
                'force_api_session' => 1,
                'format' => 'original',
            ]);
            $this->assertNotEmpty($result);
        } finally {
            unset($_GET['token_auth']);
            unset($_GET['force_api_session']);
        }
    }

    private function assertMd5($string)
    {
        $this->assertSame(32, strlen($string));
        $this->assertTrue(ctype_xdigit($string));
    }

    public static function getOutputPrefix()
    {
        return '';
    }

    public static function getPathToTestDirectory()
    {
        return dirname(__FILE__);
    }

    public static function provideContainerConfigBeforeClass()
    {
        return [
            'observers.global' => \Piwik\DI::add([
                [
                    'Access.Capability.addCapabilities',
                    \Piwik\DI::value(function (&$capabilities) {
                        $capabilities[] = new TestWriteCap();
                    }),
                ],
            ]),
        ];
    }
}

ApiTest::$fixture = new ManyUsers(1, 1, false);
