<refentry id="{$id}">
   <refnamediv>
    <refname>Package {$package} Constants</refname>
    <refpurpose>Constants defined in and used by {$package}</refpurpose>
   </refnamediv>
   <refsect1 id="{$id}.details">
    <title>All Constants</title>
{section name=files loop=$defines}
    <refsect2 id="{$id}.details.{$defines[files].page}">
     <title>
      Constants defined in {$defines[files].name}
     </title>
     <para>
      <table>
       <title>Constants defined in {$defines[files].name}</title>
{section name=d loop=$defines[files].defines}
{if $defines[files].defines[d].conflicts}{assign var="defineconflict" value=true}{/if}
{/section}
       <tgroup cols="{if $defineconflict}4{else}3{/if}">
        <thead>
         <row>
          <entry>Name</entry>
          <entry>Value</entry>
          <entry>Line Number</entry>
{if $defineconflict}
          <entry>Conflicts with other packages</entry>
{/if}
 	     </row>
        </thead>
        <tbody>
{section name=d loop=$defines[files].defines}
         <row>
          <entry>{$defines[files].defines[d].name}</entry>
          <entry>{$defines[files].defines[d].value}</entry>
          <entry>{$defines[files].defines[d].line_number}</entry>
{if $defineconflict}
          <entry>{$defines[files].defines[d].conflicts}</entry>
{/if}
         </row>
{/section}
        </tbody>
       </tgroup>
      </table>
     </para>
    </refsect2>
{/section}
 </refsect1>
</refentry>
<!-- Generated by phpDocumentor v {$phpdocversion} {$phpdocwebsite} -->
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
sgml-parent-document:nil
sgml-default-dtd-file:"../../../../manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->
