<refentry id="{$id}">
   <refnamediv>
    <refname>Package {$package} Global Variables</refname>
    <refpurpose>Global Variables defined in and used by {$package}</refpurpose>
   </refnamediv>
   <refsect1 id="{$id}.details">
    <title>All Global Variables</title>
{section name=files loop=$globals}
    <refsect2 id="{$id}.details.{$globals[files].page}">
     <title>
      Global Variables defined in {$globals[files].name}
     </title>
     <para>
      <table>
      <title>Global Variables defined in {$globals[files].name}</title>
{section name=d loop=$globals[files].globals}
{if $globals[files].globals[d].conflicts}{assign var="globalconflict" value=true}{/if}
{/section}
       <tgroup cols="{if $globalconflict}4{else}3{/if}">
        <thead>
         <row>
          <entry>Name</entry>
          <entry>Value</entry>
          <entry>Line Number</entry>
{if $globalconflict}
          <entry>Conflicts with other packages</entry>
{/if}
         </row>
        </thead>
        <tbody>
{section name=d loop=$globals}
         <row>
	     
<entry>{$globals[files].globals[d].name}</entry>
          <entry>{$globals[files].globals[d].value}</entry>
          <entry>{$globals[files].globals[d].line_number}</entry>
{if $globalconflict}
          <entry>{$globals[files].globals[d].conflicts}</entry>
{/if}
         </row>
{/section}
        </tbody>
       </tgroup>
      </table>
     </para>
    </refsect2>
{/section}
 </refsect1>
</refentry>
<!-- Generated by phpDocumentor v {$phpdocversion} {$phpdocwebsite} -->
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
sgml-parent-document:nil
sgml-default-dtd-file:"../../../../manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->
