-- Basic tracking tables for testing with auto random keys

create table log_action
(
	idaction bigint PRIMARY KEY AUTO_RANDOM(3),
	name varchar(4096) null,
	hash int unsigned not null,
	type tinyint unsigned null,
	url_prefix tinyint(2) null
);
create index index_type_hash on log_action (type, hash);

create table log_link_visit_action
(
	idlink_va bigint PRIMARY KEY AUTO_RANDOM(3),
	idsite int unsigned not null,
	idvisitor binary(8) not null,
	idvisit bigint(20) not null,
	idaction_url_ref bigint(20) default 0 null,
	idaction_name_ref bigint(20) null,
	custom_float double null,
	pageview_position mediumint unsigned null,
	time_spent int unsigned null,
	custom_dimension_1 varchar(255) null,
	custom_dimension_2 varchar(255) null,
	custom_dimension_3 varchar(255) null,
	custom_dimension_4 varchar(255) null,
	custom_dimension_5 varchar(255) null,
	server_time datetime not null,
	idpageview char(6) null,
	idaction_name bigint(20) null,
	idaction_url bigint(20) null,
	search_cat varchar(200) null,
	search_count int unsigned null,
	time_spent_ref_action int unsigned null,
	idaction_product_cat bigint(20) null,
	idaction_product_cat2 bigint(20) null,
	idaction_product_cat3 bigint(20) null,
	idaction_product_cat4 bigint(20) null,
	idaction_product_cat5 bigint(20) null,
	idaction_product_name bigint(20) null,
	product_price double null,
	idaction_product_sku bigint(20) null,
	idaction_event_action bigint(20) null,
	idaction_event_category bigint(20) null,
	idaction_content_interaction bigint(20) null,
	idaction_content_name bigint(20) null,
	idaction_content_piece bigint(20) null,
	idaction_content_target bigint(20) null,
	time_dom_completion mediumint(10) unsigned null,
	time_dom_processing mediumint(10) unsigned null,
	time_network mediumint(10) unsigned null,
	time_on_load mediumint(10) unsigned null,
	time_server mediumint(10) unsigned null,
	time_transfer mediumint(10) unsigned null,
	bandwidth bigint(15) unsigned null,
	custom_var_k1 varchar(200) null,
	custom_var_v1 varchar(200) null,
	custom_var_k2 varchar(200) null,
	custom_var_v2 varchar(200) null,
	custom_var_k3 varchar(200) null,
	custom_var_v3 varchar(200) null,
	custom_var_k4 varchar(200) null,
	custom_var_v4 varchar(200) null,
	custom_var_k5 varchar(200) null,
	custom_var_v5 varchar(200) null
);
create index index_idsite_servertime on log_link_visit_action (idsite, server_time);
create index index_idvisit on log_link_visit_action (idvisit);

create table log_visit
(
	idvisit bigint PRIMARY KEY AUTO_RANDOM(3),
	idsite int unsigned not null,
	idvisitor binary(8) not null,
	visit_last_action_time datetime not null,
	config_id binary(8) not null,
	location_ip varbinary(16) not null,
	last_idlink_va bigint(20) null,
	custom_dimension_1 varchar(255) null,
	custom_dimension_2 varchar(255) null,
	custom_dimension_3 varchar(255) null,
	custom_dimension_4 varchar(255) null,
	custom_dimension_5 varchar(255) null,
	profilable tinyint(1) null,
	user_id varchar(200) null,
	visit_first_action_time datetime not null,
	visit_goal_buyer tinyint(1) null,
	visit_goal_converted tinyint(1) null,
	visitor_returning tinyint(1) null,
	visitor_seconds_since_first int(11) unsigned null,
	visitor_seconds_since_order int(11) unsigned null,
	visitor_count_visits int(11) unsigned default 0 not null,
	visit_entry_idaction_name bigint(20) null,
	visit_entry_idaction_url bigint(20) null,
	visit_exit_idaction_name bigint(20) null,
	visit_exit_idaction_url bigint(20) default 0 null,
	visit_total_actions int(11) unsigned null,
	visit_total_interactions mediumint unsigned default 0 null,
	visit_total_searches smallint unsigned null,
	referer_keyword varchar(255) null,
	referer_name varchar(255) null,
	referer_type tinyint(1) unsigned null,
	referer_url varchar(1500) null,
	location_browser_lang varchar(20) null,
	config_browser_engine varchar(10) null,
	config_browser_name varchar(40) null,
	config_browser_version varchar(20) null,
	config_client_type tinyint(1) null,
	config_device_brand varchar(100) null,
	config_device_model varchar(100) null,
	config_device_type tinyint(100) null,
	config_os char(3) null,
	config_os_version varchar(100) null,
	visit_total_events int(11) unsigned null,
	visitor_localtime time null,
	visitor_seconds_since_last int(11) unsigned null,
	config_resolution varchar(18) null,
	config_cookie tinyint(1) null,
	config_flash tinyint(1) null,
	config_java tinyint(1) null,
	config_pdf tinyint(1) null,
	config_quicktime tinyint(1) null,
	config_realplayer tinyint(1) null,
	config_silverlight tinyint(1) null,
	config_windowsmedia tinyint(1) null,
	visit_total_time int(11) unsigned not null,
	location_city varchar(255) null,
	location_country char(3) null,
	location_latitude decimal(9,6) null,
	location_longitude decimal(9,6) null,
	location_region char(3) null,
	location_subnetwork varchar(100) null,
	campaign_content varchar(255) null,
	campaign_group varchar(255) null,
	campaign_id varchar(100) null,
	campaign_keyword varchar(255) null,
	campaign_medium varchar(255) null,
	campaign_name varchar(255) null,
	campaign_placement varchar(100) null,
	campaign_source varchar(255) null,
	custom_var_k1 varchar(200) null,
	custom_var_v1 varchar(200) null,
	custom_var_k2 varchar(200) null,
	custom_var_v2 varchar(200) null,
	custom_var_k3 varchar(200) null,
	custom_var_v3 varchar(200) null,
	custom_var_k4 varchar(200) null,
	custom_var_v4 varchar(200) null,
	custom_var_k5 varchar(200) null,
	custom_var_v5 varchar(200) null,
	location_provider varchar(200) null
);
create index index_idsite_config_datetime on log_visit (idsite, config_id, visit_last_action_time);
create index index_idsite_datetime on log_visit (idsite, visit_last_action_time);
create index index_idsite_idvisitor on log_visit (idsite, idvisitor);

-- Include so that compound keys can be tested ?
create table log_conversion
(
	idvisit bigint(20) unsigned not null,
	idsite int unsigned not null,
	idvisitor binary(8) not null,
	server_time datetime not null,
	idaction_url bigint(20) null,
	idlink_va bigint(20) unsigned null,
	idgoal int(10) not null,
	buster int unsigned not null,
	idorder varchar(100) null,
	items smallint unsigned null,
	url varchar(4096) not null,
	revenue float null,
	revenue_shipping double null,
	revenue_subtotal double null,
	revenue_tax double null,
	revenue_discount double null,
	custom_dimension_1 varchar(255) null,
	custom_dimension_2 varchar(255) null,
	custom_dimension_3 varchar(255) null,
	custom_dimension_4 varchar(255) null,
	custom_dimension_5 varchar(255) null,
	visitor_returning tinyint(1) null,
	visitor_seconds_since_first int(11) unsigned null,
	visitor_seconds_since_order int(11) unsigned null,
	visitor_count_visits int(11) unsigned default 0 not null,
	referer_keyword varchar(255) null,
	referer_name varchar(255) null,
	referer_type tinyint(1) unsigned null,
	config_browser_name varchar(40) null,
	config_client_type tinyint(1) null,
	config_device_brand varchar(100) null,
	config_device_model varchar(100) null,
	config_device_type tinyint(100) null,
	location_city varchar(255) null,
	location_country char(3) null,
	location_latitude decimal(9,6) null,
	location_longitude decimal(9,6) null,
	location_region char(3) null,
	campaign_content varchar(255) null,
	campaign_group varchar(255) null,
	campaign_id varchar(100) null,
	campaign_keyword varchar(255) null,
	campaign_medium varchar(255) null,
	campaign_name varchar(255) null,
	campaign_placement varchar(100) null,
	campaign_source varchar(255) null,
	custom_var_k1 varchar(200) null,
	custom_var_v1 varchar(200) null,
	custom_var_k2 varchar(200) null,
	custom_var_v2 varchar(200) null,
	custom_var_k3 varchar(200) null,
	custom_var_v3 varchar(200) null,
	custom_var_k4 varchar(200) null,
	custom_var_v4 varchar(200) null,
	custom_var_k5 varchar(200) null,
	custom_var_v5 varchar(200) null,
	primary key (idvisit, idgoal, buster),
	constraint unique_idsite_idorder
		unique (idsite, idorder)
);
create index index_idsite_datetime on log_conversion (idsite, server_time);

