/*!
 * Matomo - free/libre analytics platform
 *
 * @link    https://matomo.org
 * @license https://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */

import { defineConfig } from 'vite';
import path from 'node:path';

// Builds the shared CoreVue polyfill bundle. Unlike the per-plugin libraries this bundle is fully
// self-contained (no externals): it ships core-js, DOMPurify, tslib and the AbortController
// polyfill, and exposes helpers such as window.tslib / window.vueSanitize. BuildPolyfill.php runs
// this config twice, toggling minification through MATOMO_VUE_PHASE.
//
// The set of core-js modules to bundle is not selected here: src/corejs-imports.generated.ts holds
// an explicit `import 'core-js/modules/...'` per polyfill actually used across plugins/*/vue/src
// (regenerated by scripts/generate-corejs-imports.mjs before this config runs). esbuild bundles
// those imports directly, so no Babel/preset-env expansion step is needed.
const isMin = process.env.MATOMO_VUE_PHASE === 'min';

export default defineConfig({
  // core-js bundles exotic Unicode whitespace constants; emit them as \uXXXX escapes so the bundle
  // stays ASCII (Matomo's file-hygiene check rejects unusual literal space characters).
  esbuild: {
    charset: 'ascii',
  },
  build: {
    outDir: path.join(__dirname, 'dist'),
    emptyOutDir: false,
    target: 'es2015',
    minify: isMin ? 'terser' : false,
    terserOptions: { format: { ascii_only: true } },
    sourcemap: false,
    chunkSizeWarningLimit: 100000,
    lib: {
      entry: path.join(__dirname, 'src', 'index.ts'),
      name: 'MatomoPolyfills',
      formats: ['iife'],
      fileName: () => (isMin ? 'MatomoPolyfills.min.js' : 'MatomoPolyfills.js'),
    },
  },
});
