#!/usr/bin/env bash
#
# Auto-configures the web container platform so UI screenshot tests can match
# CI screenshots. Pins the container to linux/amd64 (the CI architecture)
# everywhere except Apple Silicon Macs without Rosetta, where amd64 emulation
# would crash Chromium.
#
# Run as a DDEV pre-start host hook (see .ddev/config.yaml).

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OVERRIDE_FILE="${PROJECT_DIR}/.ddev/docker-compose.override.yaml"

write_amd64_override() {
    cat > "${OVERRIDE_FILE}" <<'EOF'
# Auto-generated by .ddev/scripts/configure-platform.sh -- do not edit.
# Pins the web container to linux/amd64 so UI screenshot tests render
# identically to CI. Regenerated on every "ddev start" / "ddev restart".
services:
  web:
    platform: linux/amd64
EOF
}

warn_no_rosetta() {
    cat <<'EOF'

────────────────────────────────────────────────────────────────────────────
  Apple Silicon Mac detected without Rosetta x86_64 translation.
  UI screenshot tests will run, but rendered screenshots will NOT match CI.

  To enable CI parity:
    Colima:        colima stop
                   colima start --vm-type vz --vz-rosetta
                   ddev restart
    Docker Desktop: Settings → General →
                   "Use Rosetta for x86_64/amd64 emulation", then ddev restart
────────────────────────────────────────────────────────────────────────────

EOF
}

colima_has_rosetta() {
    local cfg
    shopt -s nullglob
    for cfg in "${HOME}/.colima/"*"/colima.yaml"; do
        if grep -qE '^rosetta:[[:space:]]*true' "${cfg}"; then
            return 0
        fi
    done
    return 1
}

docker_desktop_has_rosetta() {
    local settings="${HOME}/Library/Group Containers/group.com.docker/settings.json"
    [ -f "${settings}" ] && grep -q '"useVirtualizationFrameworkRosetta"[[:space:]]*:[[:space:]]*true' "${settings}"
}

uname_s="$(uname -s)"
uname_m="$(uname -m)"

if [ "${uname_s}" = "Darwin" ] && [ "${uname_m}" = "arm64" ]; then
    if colima_has_rosetta || docker_desktop_has_rosetta; then
        write_amd64_override
    else
        rm -f "${OVERRIDE_FILE}"
        warn_no_rosetta
    fi
else
    # Linux (any arch) or Intel Mac → pin amd64 for parity. Pin is harmless on
    # x86_64 hosts and required on hosts that would otherwise default to arm64.
    write_amd64_override
fi
