<html>
<head>
	<title>{$maintitle}</title>
			<link rel="stylesheet" href="{$subdir}media/stylesheet.css" />
			<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'/>
</head>
<body>
<div align="center"><h1>{$maintitle}</h1></div>
<b>Welcome to {$package}!</b><br />
<br />
This documentation was generated by <a href="{$phpdocwebsite}">phpDocumentor v{$phpdocversion}</a><br />
</body>
</html>