<!--
	IE 6 makes the page to wide with the following doctype. I accept
	standards if they help me, not if they make anything even harder!
//-->
<!--<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0 Transitional//EN' 'http://www.w3.org/TR/REC-html40/loose.dtd'>//-->
<!--NewPage-->
<HTML>
<HEAD>
	<!-- Generated by PhpDoc date: '{$date}' -->
	<TITLE>{$title}</TITLE>
<LINK REL ='stylesheet' TYPE='text/css' HREF='{$subdir}media/stylesheet.css' TITLE='Style'>
{if $bgleft}
<STYLE type="text/css"><!--
	BODY								{ldelim}
											background-image		: url("{$subdir}media/bg_left.png");
											background-repeat		: repeat-y;
										{rdelim}
//--></STYLE>
{/if}
</HEAD>
<BODY {if !$bgleft}BGCOLOR='white'{/if}>
<a name="top"><!-- --></a>