name: Composer update

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 5"

permissions:
  actions: read
  checks: none
  contents: write
  deployments: none
  issues: read
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v7
      with:
        ref: '5.x-dev'
        lfs: false
        persist-credentials: false
    - name: Install composer dependencies
      run: composer install
    - name: Prepare branches
      run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"

          git remote add upstream "https://github.com/${GITHUB_REPOSITORY}.git"

          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}" --delete composer-update || true
          git branch -D composer-update || true
          git fetch upstream 5.x-dev
          git checkout -f upstream/5.x-dev
          git branch composer-update
          git checkout -f composer-update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update composer dependencies
      id: update
      run: |
          composer update --no-ansi 2>&1 | tee COMPOSER_RAW

          {
            echo 'composer update log:'
            echo '```'
            cat COMPOSER_RAW
            echo '```'
          } > COMPOSER_LOG

          # abort here if no change available
          if git diff --quiet -- composer.lock
          then
              exit 0
          fi

          git add "composer.lock"
          echo "message=$(jq -aRs < COMPOSER_LOG)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Push changes
      run: |
          git commit -m "Update composer dependencies"
          git push --set-upstream "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}" composer-update
      shell: bash
      if: steps.update.outputs.message
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create PR
      env:
        CUSTOM_ACCESS_TOKEN: ${{ secrets.CUSTOM_ACCESS_TOKEN }}
        PR_BODY: ${{ steps.update.outputs.message }}
      run: |
          jq -n --argjson body "$PR_BODY" \
              '{title:"[automatic composer updates]", body:$body, head:"composer-update", base:"5.x-dev"}' \
            | curl \
                   --request POST \
                   --header "authorization: Bearer ${CUSTOM_ACCESS_TOKEN}" \
                   --header 'content-type: application/json' \
                   --data @- \
                   --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls"
      shell: bash
      if: steps.update.outputs.message
