name: Stylelint

on: pull_request

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  phpcs:
    name: stylelinter
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          lfs: false
          persist-credentials: false
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
      - uses: actions/cache@v6
        with:
          path: node_modules
          key: stylelint-node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: stylelint
        run: |
          npm install --ignore-scripts --no-audit --no-fund
          npx stylelint "**/*.{css,less}" -f github
