name: Update Intl data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

permissions:
  actions: read
  checks: none
  contents: write
  deployments: none
  issues: read
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: "Fetch latest CLDR version"
        id: cldr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CLDRRELEASES=$( curl \
                 --request GET \
                 --header "authorization: Bearer ${GITHUB_TOKEN}" \
                 --header 'content-type: application/json' \
                 --url https://api.github.com/repos/unicode-org/cldr-json/releases?per_page=15 )
          for row in $(echo "${CLDRRELEASES}" | jq -r '.[] | @base64'); do
            _jq() {
              echo "${row}" | base64 --decode | jq -r "${1}"
            }
            if [[ $(_jq '.prerelease') == false ]]
            then
              echo "cldr-version=$(_jq '.tag_name')" >> "$GITHUB_OUTPUT"
              break
            fi
          done
        shell: bash
      - name: "Check CLDR version"
        if: steps.cldr.outputs.cldr-version == ''
        uses: actions/github-script@v9
        with:
          script: |
            core.setFailed('Unable to find current CLDR version')
      - uses: actions/checkout@v6
        with:
          lfs: false
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Quick Matomo Install
        run: |
          cat <<-EOF > ./config/config.ini.php
          [General]
          always_load_commands_from_plugin=Intl

          [Development]
          enabled = 1
          EOF

          cat ./config/config.ini.php
      - name: Prepare git config
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}" --delete update-intl || true
          git branch -D update-intl || true
          git branch update-intl
          git checkout -f update-intl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Intl data
        env:
          CLDR_VERSION: ${{ steps.cldr.outputs.cldr-version }}
        run: php ./console translations:generate-intl-data --cldr-version="$CLDR_VERSION"
      - name: Push changes
        id: push
        run: |
          if [[ $( git diff --numstat plugins/Intl/lang/*.json ) ]]
          then
            cd "$GITHUB_WORKSPACE"
            git add plugins/Intl/lang/*.json
            git commit -m "Update Intl data from CLDR $CLDR_VERSION"
            git push --set-upstream "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}" update-intl
            echo "updated=1" >> "$GITHUB_OUTPUT"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLDR_VERSION: ${{ steps.cldr.outputs.cldr-version }}
      - name: Create PR
        env:
          CUSTOM_ACCESS_TOKEN: ${{ secrets.CUSTOM_ACCESS_TOKEN }}
          CLDR_VERSION: ${{ steps.cldr.outputs.cldr-version }}
        run: |
          jq -n --arg cldr "$CLDR_VERSION" \
              '{title:("[automatic Intl data updates from CLDR " + $cldr + "]"), body:("Updated Intl plugin data with changes from CLDR " + $cldr), head:"update-intl", base:"5.x-dev"}' \
            | curl \
                 --request POST \
                 --header "authorization: Bearer ${CUSTOM_ACCESS_TOKEN}" \
                 --header 'content-type: application/json' \
                 --data @- \
                 --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls"
        shell: bash
        if: steps.push.outputs.updated
